name: 'A comple Job v1'
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "In set up"
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "In build"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "In test"